name: Lint

on:
    push:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Install Dependencies
              run: yarn

            - name: Run ESLint
              run: yarn lint --max-warnings=0
